[2024-05-10T23:31:09.254+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-05-10T23:32:05.110+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-05-10T23:32:36.088+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-05-10T23:33:28.691+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-05-10T23:35:23.835+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: process_sales.extract_data_from_api scheduled__2022-08-11T01:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
